### ISSUE TITLE
Non-existing entities `moduleLink` and `hxModuleLink`

### ISSUE THREAD

**Issue by jonthans** [ocadotechnology/hexagonjs-site#105] opened 2016-08-29 10:19 UTC
Some of the pages that stem from older versions use `@moduleLink` and `@hxModuleLink` entities that don't seem to exist anymore which leads to confusing docs like `The available options can be found on the page` instead of `The available options can be found on the hx-filter page`

**Comment by jmsmyth** [comment] 2016-08-29 14:48
Duplicate of #74

**Closed as completed by jmsmyth** 2016-08-29 14:48 UTC
